-- (
-- SELECT FIRST_NAME FROM ACTOR
-- ORDER BY FIRST_NAME
-- )
-- UNION ALL
-- (
-- SELECT FIRST_NAME FROM CUSTOMER
-- ORDER BY FIRST_NAME
-- );

-- (
-- SELECT FIRST_NAME FROM ACTOR
-- ORDER BY FIRST_NAME
-- )
-- INTERSECT
-- (
-- SELECT FIRST_NAME FROM CUSTOMER
-- ORDER BY FIRST_NAME
-- );

(
SELECT FIRST_NAME FROM ACTOR
ORDER BY FIRST_NAME
)
EXCEPT
(
SELECT FIRST_NAME FROM CUSTOMER
ORDER BY FIRST_NAME
);